### ISSUE TITLE
Some suggestions for the menu

### ISSUE THREAD

**Issue by aukondk** [hermitretro/fuse-hermitretro#2]
1. With "Open" now in the main menu, the shortcut key clashes for the one for "Options". Maybe use "p" for Options or rename it to "Settings"
2. The file list doesn't seem to show all the files in a folder if there is more than about 30. It doesn't scroll and there are some missing from the middle of the list rather than the end.
3. Can we have a way to save settings like the filter or machine?
4. Maybe hide some advanced menu for things like fast load on/off.

**Comment by hermitretro** [comment]
1) that's a bug
2) has been created as an issue for spi-fat-fuse repo
3) is in progress
4) definitely doable. Do you have a list of "normal" Fuse options you want?

**Comment by aukondk** [comment]
I wanted to disable fast loading but on my version of Fuse on the desktop (1.5.7) I can't seem to do that without also disabling the tape traps and playing the tape manually. Your version seems to load tape files fast and silent but not instantly. I like this but I sometimes would like to see and hear the long version.

Emulation speed would be good. Some games feel a bit nicer at 150%.

**Comment by hermitretro** [comment]
OK, I'll have a think about it. The menus in Fuse are done at compile-time, not run-time, so, much as I like the idea of a "Switch on Advanced Stuff" option, it might be a bit of bigger change to do. I'm kinda loathe to just either adding a bunch of confusing stuff people, in general, might not want. But I suppose an "Advanced" menu might be the place for that and just hope there isn't too much of it! :-)

**Comment by hermitretro** [comment]
Issue 2 above is now fixed in: https://github.com/hermitretro/spi-fat-fuse/commit/3c2edab9979b519d161feaa0a6e937ba09147066

**Comment by hermitretro** [comment]
Points 1, 3, 4 resolved in commit 537f2bb8c3fa5a8b7b40085a3a92ae4f5ac41f56 (branch hermitretro-zxzero-1-0-2)
