### ISSUE TITLE
ZXZero Kempston random inputs

### ISSUE THREAD

**Issue by aukondk** [hermitretro/fuse-hermitretro#3]
When a game is set to use Kempston it will act as if it is receiving random inputs, direction and button presses.

This happens even if the joysticks are set to none in the Fuse menu and the joystick is unplugged.

The joystick itself works fine in the menu and if the game can be set to use Sinclair 1 etc. If set to Kempston the hardware inputs don't seem to be recognized at all, only the mystery random signals.

**Comment by hermitretro** [comment]
Fixed in commit 537f2bb8c3fa5a8b7b40085a3a92ae4f5ac41f56.

The Z80 format acts as a complete machine snapshot including joystick data. This resets and overwrites the ZXZero settings which makes the Kempston interface act in random ways.

**Comment by hermitretro** [comment]
Fix is to make Kempston non-optional as a machine parameters for ZXZero.
